### ISSUE TITLE
superclass must be a Class (Module given) (Rails 5, Ruby 2.2.2)

### ISSUE THREAD

**Issue by Jamevidi** [godfat/zbatery#2]
Maybe this great gem is not maintained. I log this issue anyways. :)

as an error while trying to load the gem 'zbatery'. (Bundler::GemRequireError)
Gem Load Error is: superclass must be a Class (Module given)
Backtrace for gem load error is:
/Users/user/.rvm/gems/ruby-2.2.2/gems/rainbows-0.94.0/lib/rainbows/http_response.rb:6:in `<module:Rainbows>'
/Users/user/.rvm/gems/ruby-2.2.2/gems/rainbows-0.94.0/lib/rainbows/http_response.rb:4:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.2.2/gems/rainbows-0.94.0/lib/rainbows.rb:32:in `require'

**Comment by godfat** [comment]
This repository was merely used to store my patches for zbatery. Could you please report this to the official mailing list instead?

The mailing list is rainbows-public@bogomips.org

According to the document: http://zbatery.bogomip.org/

As far as I know, this gem is no longer actively developed, but if you report any issues, I believe Eric would be love to look into them and fix them accordingly.
